[tools]
"aqua:tailwindlabs/tailwindcss" = "latest"
bitwarden = "latest"
bun = "latest"
chezmoi = "latest"
claude = "latest"
codex = "latest"
crush = "latest"
deno = "latest"
ghq = "latest"
gitleaks = "latest"
go = "latest"
"github:cli/cli" = "latest"
"github:microsoft/ghqr" = "latest"
herdr = "latest"
lazygit = "latest"
node = "latest"
"npm:@continuedev/cli" = "latest"
"npm:@playwright/cli" = "latest"
"npm:@steipete/oracle" = "0.15.1"
"npm:vibium" = "latest"
ollama = "latest"
opencode = "1.17.15"
qwen = "latest"
terraform = "latest"
uv = "latest"
wrangler = { version = "latest", allow_builds = ["esbuild", "sharp", "workerd"] }
yt-dlp = { version = "latest", rename_exe = "yt-dlp" }
"go:golang.org/x/tools/gopls" = "latest"
"github:stripe/stripe-cli" = "latest"
